#!/bin/sh

mkdir -p /tmp/tailscale
/var/runtime/tailscaled --tun=userspace-networking --outbound-http-proxy-listen=localhost:1055 &
/var/runtime/tailscale up --authkey=${TAILSCALE_AUTHKEY} --accept-routes --netfilter-mode=on
echo Tailscale started
grpc_proxy=http://localhost:1055/ node lib/worker.js
